# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diag_quad_mat <- function(A, B) {
    .Call(`_deepgp_diag_quad_mat`, A, B)
}

Exp2 <- function(distmat, tau2, theta, g) {
    .Call(`_deepgp_Exp2`, distmat, tau2, theta, g)
}

Exp2Grad <- function(x1, x2, grad1, grad2, tau2, theta, g) {
    .Call(`_deepgp_Exp2Grad`, x1, x2, grad1, grad2, tau2, theta, g)
}

Exp2Sep <- function(x1, x2, tau2, theta, g) {
    .Call(`_deepgp_Exp2Sep`, x1, x2, tau2, theta, g)
}

Exp2SepGrad <- function(x1, x2, grad1, grad2, tau2, theta, g) {
    .Call(`_deepgp_Exp2SepGrad`, x1, x2, grad1, grad2, tau2, theta, g)
}

Matern <- function(distmat, tau2, theta, g, v) {
    .Call(`_deepgp_Matern`, distmat, tau2, theta, g, v)
}

MaternSep <- function(x1, x2, tau2, theta, g, v) {
    .Call(`_deepgp_MaternSep`, x1, x2, tau2, theta, g, v)
}

forward_solve_raw <- function(U, z, NNarray) {
    .Call(`_deepgp_forward_solve_raw`, U, z, NNarray)
}

U_entries <- function(cores, x, NNarray, tau2, theta, g, v) {
    .Call(`_deepgp_U_entries`, cores, x, NNarray, tau2, theta, g, v)
}

U_entries_grad <- function(cores, x, NNarray, grad, tau2, theta, g, v) {
    .Call(`_deepgp_U_entries_grad`, cores, x, NNarray, grad, tau2, theta, g, v)
}

U_entries_sep <- function(cores, x, NNarray, tau2, theta, g, v) {
    .Call(`_deepgp_U_entries_sep`, cores, x, NNarray, tau2, theta, g, v)
}

U_entries_sep_grad <- function(cores, x, NNarray, grad, tau2, theta, g, v) {
    .Call(`_deepgp_U_entries_sep_grad`, cores, x, NNarray, grad, tau2, theta, g, v)
}

check_omp <- function() {
    invisible(.Call(`_deepgp_check_omp`))
}

row_col_pointers <- function(NNarray) {
    .Call(`_deepgp_row_col_pointers`, NNarray)
}

