# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rev_matrix <- function(x) {
    .Call(`_deepgp_rev_matrix`, x)
}

Exp2Fun <- function(distmat, covparms) {
    .Call(`_deepgp_Exp2Fun`, distmat, covparms)
}

MaternFun <- function(distmat, covparms) {
    .Call(`_deepgp_MaternFun`, distmat, covparms)
}

U_entries <- function(Ncores, n, locs, revNNarray, revCondOnLatent, covparms) {
    .Call(`_deepgp_U_entries`, Ncores, n, locs, revNNarray, revCondOnLatent, covparms)
}

check_omp <- function() {
    invisible(.Call(`_deepgp_check_omp`))
}

